language: python
python: 3.6

install:
  - pip install pycodestyle flake8 isort
  - pip install -r requirements.txt
  - pip install -U pytest

script:
  # todo: use flake8
  - pycodestyle --show-source --max-line-length=120 --show-pep8 .

  # Running some tests.
  - apistar test
  - pytest
