language: python
python: 3.6

before_install:
  - sudo add-apt-repository ppa:rethinkdb/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install rethinkdb -y

install:
  - pip install pycodestyle flake8 isort
  - pip install -r requirements.txt
  - pip install -U pytest

before_script:
  - sudo rethinkdb -http-port 8090 --daemon

script:
  # todo: use flake8
  - pycodestyle --show-source --max-line-length=120 --show-pep8 .

  # Running flask in the background.
  - FLASK_APP=app.py FLASK_DEBUG=1 flask run --port 8080 > /dev/null 2>&1 &

  # Running some tests.
  - pytest TestsBismarkReport.py
  - pytest TestsFlask.py
  - pytest TestsPlugins.py
  - pytest TestsRosetta.py
