version: '3'
services:
  rethinkdb:
    image: rethinkdb
    ports:
      - 8080:8080

    volumes:
      - ./database:/data
    command: rethinkdb --bind all -d /data

  bismark:
    image: bismark:1.2
    volumes:
      - ./settings.yml:/opt/webapp/settings.yml

    depends_on:
      - rethinkdb

    ports:
      - 8000:8000
